In [2]:
%pip install pandas 
%pip install  numpy
%pip install sqlalchemy
import numpy as np
import pandas as pd
import re
df=pd.read_csv(r'C:\Users\kanis\OneDrive\Desktop\pythonvsworksdir\lux_house\Luxury_Housing_Bangalore.csv')

Requirement already satisfied: pandas in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: numpy in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (2.3.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: sqlalchemy in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,Connectivity_Score,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846039118798,Primary,NRI,2025-03-31,7.990091,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292151871065954,Primary,Other,2024-06-30,4.839024,NaN,Under construction,NRI Desk,no,7.723898,106,NaN
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724412961911,Primary,HNI,2023-12-31,8.131315,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.
3,PROP000004,bellary road,Project_3,Embassy,6192.0,3BHK,9.396367494232896,Primary,HNI,2024-03-31,7.501657,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392444511946,Secondary,HNI,2024-12-31,4.525216,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100995,PROP004730,BELLARY ROAD,Project_229,Embassy,8546.0,5Bhk+,11.33081004147843,Secondary,CXO,2024-12-31,8.552797,6.221131,Under construction,NRI Desk,no,7.511827,22,Will buy after possession.
100996,PROP059810,Bellary Road,Project_309,Brigade,3408.0,3bhk,10.829373158307602,Primary,CXO,2024-09-30,6.879269,9.783611,Ready to move,Direct,no,9.851849,26,Agent was not responsive.
100997,PROP065099,HENNUR ROAD,Project_98,RMZ,4691.0,4BHK,11.183303152058548,Primary,NRI,2023-12-31,6.753812,8.383013,Under construction,Broker,no,9.101604,44,Loved the amenities!
100998,PROP093022,rajajinagar,Project_21,Embassy,7435.0,3BHK,10.914156376035923,Secondary,Other,2024-06-30,4.437787,5.756247,Under construction,Broker,yes,8.588551,66,Excellent location!
100999,PROP023826,whitefield,Project_325,L&T Realty,3218.0,4bhk,₹13.27 Cr,Primary,Startup Founder,2023-12-31,7.760416,9.989290,Under construction,Direct,yes,9.917647,58,Loved the amenities!

In [4]:
df.columns

Index(['Property_ID', 'Micro_Market', 'Project_Name', 'Developer_Name',
       'Unit_Size_Sqft', 'Configuration', 'Ticket_Price_Cr',
       'Transaction_Type', 'Buyer_Type', 'Purchase_Quarter',
       'Connectivity_Score', 'Amenity_Score', 'Possession_Status',
       'Sales_Channel', 'NRI_Buyer', 'Locality_Infra_Score',
       'Avg_Traffic_Time_Min', 'Buyer_Comments'],
      dtype='object')

In [5]:
df['Micro_Market'].unique()

array(['Sarjapur Road', 'Indiranagar', 'Bannerghatta Road',
       'bellary road', 'Koramangala', 'YELAHANKA', 'whitefield',
       'sarjapur road', 'JP NAGAR', 'Rajajinagar', 'koramangala',
       'WHITEFIELD', 'indiranagar', 'jayanagar', 'Whitefield', 'DOMLUR',
       'yelahanka', 'Mg Road', 'HENNUR ROAD', 'Jayanagar', 'Domlur',
       'Electronic City', 'Hebbal', 'mg road', 'jp nagar',
       'BANNERGHATTA ROAD', 'MG ROAD', 'KANAKAPURA ROAD', 'HEBBAL',
       'BELLARY ROAD', 'electronic city', 'ELECTRONIC CITY',
       'Bellary Road', 'Hennur Road', 'rajajinagar', 'Kanakapura Road',
       'INDIRANAGAR', 'hennur road', 'kanakapura road', 'domlur',
       'bannerghatta road', 'RAJAJINAGAR', 'hebbal', 'Yelahanka',
       'SARJAPUR ROAD', 'KORAMANGALA', 'Jp Nagar', 'JAYANAGAR'],
      dtype=object)

In [6]:
df['Micro_Market']=df['Micro_Market'].str.title()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101000 entries, 0 to 100999
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           101000 non-null  object
 1   Micro_Market          101000 non-null  object
 2   Project_Name          101000 non-null  object
 3   Developer_Name        101000 non-null  object
 4   Unit_Size_Sqft        90954 non-null   float64
 5   Configuration         101000 non-null  object
 6   Ticket_Price_Cr       90981 non-null   object
 7   Transaction_Type      101000 non-null  object
 8   Buyer_Type            101000 non-null  object
 9   Purchase_Quarter      101000 non-null  object
 10  Connectivity_Score    101000 non-null  float64
 11  Amenity_Score         90910 non-null   float64
 12  Possession_Status     101000 non-null  object
 13  Sales_Channel         101000 non-null  object
 14  NRI_Buyer             101000 non-null  object
 15  Locality_Infra_Score  101000 non-null  float64
 16  Avg_Traffic_Time_Min  101000 non-null  int64
 17  Buyer_Comments        82713 non-null   object
dtypes: float64(4), int64(1), object(13)
memory usage: 13.9+ MB

In [8]:
df['Developer_Name'].unique()

array(['RMZ', 'Puravankara', 'Tata Housing', 'Embassy', 'SNN Raj',
       'Brigade', 'Prestige', 'Total Environment', 'Godrej', 'L&T Realty',
       'Sobha'], dtype=object)

In [9]:
df['Developer_Name'].str.title()

0                  Rmz
1          Puravankara
2         Tata Housing
3              Embassy
4              Snn Raj
              ...
100995         Embassy
100996         Brigade
100997             Rmz
100998         Embassy
100999      L&T Realty
Name: Developer_Name, Length: 101000, dtype: object

In [10]:
df["Ticket_Price_Cr"] = (
    df["Ticket_Price_Cr"]
    .astype(str)
    .str.replace(r"[^\d.]", "", regex=True)   # remove non-numeric chars
    .replace("", np.nan)                      # convert blanks to NaN
    .astype(float)
)

# Fill NaN with mean (safe assignment, no warning)
mean_price = df["Ticket_Price_Cr"].mean()
df["Ticket_Price_Cr"] = df["Ticket_Price_Cr"].fillna(mean_price)

In [11]:
df["Amenity_Score"]=df["Amenity_Score"].fillna(df["Amenity_Score"].mean())
df["Unit_Size_Sqft"]=df["Unit_Size_Sqft"].fillna(df["Unit_Size_Sqft"].mean())
df['Buyer_Comments']=df['Buyer_Comments'].fillna('No Coments')

In [12]:
df["Price_per_Sqft"] = (df["Ticket_Price_Cr"] * 10000000) / df["Unit_Size_Sqft"]

In [13]:
df["Booking_Flag"] = df["Transaction_Type"].apply(
        lambda x: 1 if str(x).lower() == "primary" else 0)

In [14]:
df['Purchase_Quarter'] = pd.to_datetime(df['Purchase_Quarter'])
df['Quarter_Number'] = df['Purchase_Quarter'].dt.quarter

In [16]:
df.duplicated().sum()

np.int64(1000)

In [20]:
df=df.drop_duplicates()

In [21]:
df

,Property_ID,Micro_Market,Project_Name,Developer_Name,Unit_Size_Sqft,Configuration,Ticket_Price_Cr,Transaction_Type,Buyer_Type,Purchase_Quarter,...,Amenity_Score,Possession_Status,Sales_Channel,NRI_Buyer,Locality_Infra_Score,Avg_Traffic_Time_Min,Buyer_Comments,Price_per_Sqft,Booking_Flag,Quarter_Number
0,PROP000001,Sarjapur Road,Project_0,RMZ,4025.0,4bhk,12.750846,Primary,NRI,2025-03-31,...,5.462863,Launch,Broker,yes,9.212491,18,Loved the amenities!,31679.120594,1,1
1,PROP000002,Indiranagar,Project_1,Puravankara,5760.0,3Bhk,16.292152,Primary,Other,2024-06-30,...,7.503663,Under construction,NRI Desk,no,7.723898,106,No Coments,28284.985887,1,2
2,PROP000003,Bannerghatta Road,Project_2,Tata Housing,7707.0,4bhk,10.517724,Primary,HNI,2023-12-31,...,8.669227,Ready to move,Direct,yes,6.985493,113,Agent was not responsive.,13646.976013,1,4
3,PROP000004,Bellary Road,Project_3,Embassy,6192.0,3BHK,9.396367,Primary,HNI,2024-03-31,...,5.720246,Ready to move,Online,yes,6.100929,106,Excellent location!,15175.012103,1,1
4,PROP000005,Koramangala,Project_4,SNN Raj,7147.0,4Bhk,15.345392,Secondary,HNI,2024-12-31,...,8.609649,Under construction,Broker,no,5.312510,18,Too far from my office.,21471.096187,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,PROP099996,Bellary Road,Project_495,L&T Realty,5550.0,5Bhk+,10.185193,Primary,NRI,2023-12-31,...,7.503663,Under construction,Online,yes,8.378800,109,Underpriced for location.,18351.699990,1,4
99996,PROP099997,Yelahanka,Project_496,L&T Realty,3171.0,4Bhk,12.272081,Secondary,Other,2023-12-31,...,6.374069,Launch,Broker,yes,7.025209,20,Great view from 15th floor.,38700.980123,0,4
99997,PROP099998,Rajajinagar,Project_497,Prestige,5599.0,4BHK,13.730179,Primary,Startup Founder,2023-09-30,...,7.482473,Launch,NRI Desk,yes,8.984990,63,No Coments,24522.555158,1,3
99998,PROP099999,Indiranagar,Project_498,SNN Raj,7342.0,4bhk,10.363989,Primary,NRI,2024-09-30,...,6.369276,Under construction,NRI Desk,yes,7.634717,89,No Coments,14116.029667,1,3
99999,PROP100000,Hennur Road,Project_499,Embassy,5016.0,5Bhk+,10.415617,Primary,Startup Founder,2024-09-30,...,5.284026,Launch,Broker,yes,6.039943,95,No Coments,20764.786348,1,3

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100000 entries, 0 to 99999
Data columns (total 21 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Property_ID           100000 non-null  object
 1   Micro_Market          100000 non-null  object
 2   Project_Name          100000 non-null  object
 3   Developer_Name        100000 non-null  object
 4   Unit_Size_Sqft        100000 non-null  float64
 5   Configuration         100000 non-null  object
 6   Ticket_Price_Cr       100000 non-null  float64
 7   Transaction_Type      100000 non-null  object
 8   Buyer_Type            100000 non-null  object
 9   Purchase_Quarter      100000 non-null  datetime64[ns]
 10  Connectivity_Score    100000 non-null  float64
 11  Amenity_Score         100000 non-null  float64
 12  Possession_Status     100000 non-null  object
 13  Sales_Channel         100000 non-null  object
 14  NRI_Buyer             100000 non-null  object
 15  Locality_Infra_Score  100000 non-null  float64
 16  Avg_Traffic_Time_Min  100000 non-null  int64
 17  Buyer_Comments        100000 non-null  object
 18  Price_per_Sqft        100000 non-null  float64
 19  Booking_Flag          100000 non-null  int64
 20  Quarter_Number        100000 non-null  int32
dtypes: datetime64[ns](1), float64(6), int32(1), int64(2), object(11)
memory usage: 16.4+ MB

In [23]:
df.to_csv("Cleaned_Luxury_Housing.csv", index=False)

In [24]:
%pip install mysql-connector-python

from sqlalchemy import create_engine, text

conn_str = f"mysql+mysqlconnector://{'2UyRh14u8Q2XGo6.root'}:{'9XIoqQ496NnHpCPV'}@{'gateway01.ap-southeast-1.prod.aws.tidbcloud.com'}:{4000}/"
engine = create_engine(conn_str)

with engine.connect() as conn:
    conn.execute(text("CREATE DATABASE IF NOT EXISTS luxury_house_sales;"))
    conn.execute(text("USE luxury_house_sales;"))
    result = conn.execute(text("SELECT DATABASE();"))
    current_db = result.scalar()
    print("✅ Current database:", current_db)

Requirement already satisfied: mysql-connector-python in c:\users\kanis\onedrive\desktop\pythonvsworksdir\lux_house\.venv\lib\site-packages (9.4.0)
Note: you may need to restart the kernel to use updated packages.
✅ Current database: luxury_house_sales

In [25]:
conn_str = f"mysql+mysqlconnector://{'2UyRh14u8Q2XGo6.root'}:{'9XIoqQ496NnHpCPV'}@{'gateway01.ap-southeast-1.prod.aws.tidbcloud.com'}:{4000}/{'luxury_house_sales'}"
engine = create_engine(conn_str)
create_table_sql = """
CREATE TABLE IF NOT EXISTS luxury_housing (
    Property_ID VARCHAR(50) PRIMARY KEY,
    Micro_Market VARCHAR(100),
    Project_Name VARCHAR(200),
    Developer_Name VARCHAR(200),
    Unit_Size_Sqft DECIMAL(10,2),
    Configuration VARCHAR(50),
    Ticket_Price_Cr DECIMAL(12,2),
    Transaction_Type VARCHAR(50),
    Buyer_Type VARCHAR(50),
    Purchase_Quarter DATE,
    Connectivity_Score DECIMAL(5,2),
    Amenity_Score DECIMAL(5,2),
    Possession_Status VARCHAR(50),
    Sales_Channel VARCHAR(50),
    NRI_Buyer VARCHAR(10),
    Locality_Infra_Score DECIMAL(5,2),
    Avg_Traffic_Time_Min INT,
    Buyer_Comments TEXT,
    Price_per_Sqft DECIMAL(12,2),
    Booking_Flag TINYINT,
    Quarter_Number INT
);
"""
with engine.connect() as conn:
    conn.execute(text(create_table_sql))
    print("✅ Table 'luxury_housing' created (if not exists).")

✅ Table 'luxury_housing' created (if not exists).

In [ ]:
'''with engine.connect() as conn:
    conn.rollback()
    print("🔄 Rolled back pending transaction.")'''

🔄 Rolled back pending transaction.

In [27]:
with engine.begin() as conn:  # begin() auto-handles commit/rollback
    df.to_sql(
        "luxury_housing",
        con=conn,
        if_exists="append",
        index=False,
        chunksize=1000,
        method="multi"
    )
print("✅ Data inserted into table 'luxury_housing'")

✅ Data inserted into table 'luxury_housing'